name: make lint

# on pull of push request of these branches do the following work flow. These is what triggers workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  eslint:
    name: start make lint
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps: # these is necessary for github to run workflow
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install
      - name: start lint
        run: make lint
      - name: Test & publish code coverage
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.COTTON_CANDY }}
        run: make test-coverage
        debug: true
        # with:
        #   coverageCommand: make test


